### ISSUE TITLE
You can property File to store Token/AccessKeys

### ISSUE THREAD

**Issue by picarro-pkumar** [ankit19apr/automation-framework#1]
https://github.com/ankit19apr/automation-framework/blob/c9039a3040f356a3a19c870d6b24a0b7970cd4ed/src/test/java/com/utility/LambdaTestUtility.java#L25

**Comment by ankit19apr** [comment]
Yes, Thanks...!!

**Comment by ankit19apr** [comment]
> https://github.com/ankit19apr/automation-framework/blob/c9039a3040f356a3a19c870d6b24a0b7970cd4ed/src/test/java/com/utility/LambdaTestUtility.java#L25

Yes, thanks

**Comment by ankit19apr** [comment]
Updated the changes
